Repository rakenduste-programmeerimine-2022/workwhen, pull requests merged in 2022-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation

#2 added wireframes
  wireframes/Bookmarks.PNG
  wireframes/Contacts.PNG
  wireframes/Dashboard.PNG
  wireframes/Schedule.PNG
  wireframes/Shift-planning.PNG
  wireframes/User-settings.PNG
  wireframes/flowchart.PNG
Labels: documentation

#3 minor fix
  README.md
Labels: documentation

#12 closes #4
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/front/App.js
  src/front/App.test.js
  src/front/index.js
  src/front/logo.svg
  src/front/reportWebVitals.js
  src/front/setupTests.js
  src/front/styles/App.css
  src/front/styles/index.css
Labels: enhancement, FE, BE

#38 User signup form for admin (closes #10)
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/index.js
  front/src/pages/Signup.js
  front/src/reportWebVitals.js
  front/wireframes/Bookmarks.PNG
  front/wireframes/Contacts.PNG
  front/wireframes/Dashboard.PNG
  front/wireframes/Schedule.PNG
  front/wireframes/Shift-planning.PNG
  front/wireframes/User-settings.PNG
  front/wireframes/flowchart.PNG
  server/.gitignore
Labels: enhancement, FE

#39 user login form (closes #9)
  front/.gitignore
  front/src/App.js
  front/src/pages/Login.js
Labels: enhancement, FE

#44 DB connected
  server/.gitignore
  server/controllers/userController.js
  server/index.js
  server/models/User.model.js
  server/package-lock.json
  server/package.json
  server/routes/user.routes.js
Labels: BE

#45 Set up FE
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/components/Navbar.js
  front/src/index.js
  front/src/pages/bookmarks.js
  front/src/pages/contacts.js
  front/src/pages/dashboard.js
  front/src/pages/schedule.js
  front/src/pages/shift-planning.js
  front/src/pages/user-settings.js
  front/src/styles/App.css
  front/src/styles/navbar.css
Labels: FE
